vim.opt.autoindent = true
vim.opt.clipboard = 'unnamedplus'
vim.opt.fileencoding = 'utf-8' 
vim.opt.linebreak = true -- Do not break lines in the middle of the word
vim.opt.mouse = 'a'
vim.opt.number = true
vim.opt.shiftwidth = 4        -- Number of spaces to use for each step of (auto)indent
vim.opt.smartindent = true
vim.opt.softtabstop = 4
--vim.opt.tabstop = 4
vim.opt.wrap = false
